package domainobjects;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link Content} specific assertions - Generated by CustomAssertionGenerator.
 */

public abstract class AbstractContentAssert<S extends AbstractContentAssert<S, A>, A extends Content> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractContentAssert}</code> to make assertions on actual Content.
   * @param actual the Content we want to make assertions on.
   */
  protected AbstractContentAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
